name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict
    #  -
    #  - name: Cache Composer packages

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress
      run: composer install --prefer-dist

    - name: Run application
      run: |        
        echo php Bin/R3m.php install r3m_io/boot  
#        echo php Bin/R3m.php install r3m_io/test
#        echo php Bin/R3m.php r3m_io/test run

    #- name: Prepare binary
    #  run: php Bin/R3m.php
    #      run: mkdir -p Bin && cp vendor/r3m_io/framework/Bin/R3m.php Bin/R3m.php && php Bin/R3m.php
    # Pest as dev added
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #  run: composer run-script test
