name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "1,6,11,16,21,26,31,36,41,46,51,56 * * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict
    #  -
    #  - name: Cache Composer packages

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress
      run: composer install --prefer-dist
#      run: composer install # not working

    - name: install application & test package
      run: |        
        php Bin/R3m.php install r3m_io/boot -force  
        php Bin/R3m.php install r3m_io/test -force
        

    ## remove the echo, echo causes success but the command fails
    # so running `install` isn't working again...
    # delete _work directory and try again
    # package r3m_io/boot seems to work
    # autoload is blocking


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: |
        php Bin/R3m.php r3m_io/test run
